FROM mcr.microsoft.com/dotnet/sdk:10.0 AS dev
WORKDIR /src
COPY ["server/CreditApp/CreditApp.csproj", "server/CreditApp/"]
RUN dotnet restore "server/CreditApp/CreditApp.csproj"
COPY server/ server/
WORKDIR "/src/server/CreditApp"
EXPOSE 8080
EXPOSE 8081
ENV ASPNETCORE_URLS=http://+:8080
CMD ["dotnet", "watch", "run", "--no-launch-profile", "--urls", "http://0.0.0.0:8080"]